# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/mobvoi/mooneye/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/mobvoi/mooneye/proprietary/etc/firmware/WIFI_RAM_CODE_MT6630:system/etc/firmware/WIFI_RAM_CODE_MT6630 \
    vendor/mobvoi/mooneye/proprietary/etc/firmware/WIFI_RAM_CODE_SOC:system/etc/firmware/WIFI_RAM_CODE_SOC \
    vendor/mobvoi/mooneye/proprietary/etc/firmware/WMT.cfg:system/etc/firmware/WMT.cfg \
    vendor/mobvoi/mooneye/proprietary/etc/firmware/mt6630_ant_m1.cfg:system/etc/firmware/mt6630_ant_m1.cfg \
    vendor/mobvoi/mooneye/proprietary/etc/firmware/mt6630_patch_e1_hdr.bin:system/etc/firmware/mt6630_patch_e1_hdr.bin \
    vendor/mobvoi/mooneye/proprietary/etc/firmware/mt6630_patch_e2_hdr.bin:system/etc/firmware/mt6630_patch_e2_hdr.bin \
    vendor/mobvoi/mooneye/proprietary/etc/firmware/mt6630_patch_e3_0_hdr.bin:system/etc/firmware/mt6630_patch_e3_0_hdr.bin \
    vendor/mobvoi/mooneye/proprietary/etc/firmware/mt6630_patch_e3_1_hdr.bin:system/etc/firmware/mt6630_patch_e3_1_hdr.bin \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/6620_launcher:system/vendor/bin/6620_launcher \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/6620_wmt_concurrency:system/vendor/bin/6620_wmt_concurrency \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/6620_wmt_lpbk:system/vendor/bin/6620_wmt_lpbk \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/factory:system/vendor/bin/factory \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/hw/rild:system/vendor/bin/hw/rild \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/meta_tst:system/vendor/bin/meta_tst \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/mnld:system/vendor/bin/mnld \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/nvram_daemon:system/vendor/bin/nvram_daemon \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/stp_dump3:system/vendor/bin/stp_dump3 \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/thermal_manager:system/vendor/bin/thermal_manager \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/wlan_assistant:system/vendor/bin/wlan_assistant \
    vendor/mobvoi/mooneye/proprietary/system/vendor/bin/wmt_loader:system/vendor/bin/wmt_loader \
    vendor/mobvoi/mooneye/proprietary/system/vendor/compatibility_matrix.xml:system/vendor/compatibility_matrix.xml \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/factory.ini:system/vendor/etc/factory.ini \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/init/6620_launcher.rc:system/vendor/etc/init/6620_launcher.rc \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/init/mnld.rc:system/vendor/etc/init/mnld.rc \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/init/nvram_daemon.rc:system/vendor/etc/init/nvram_daemon.rc \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/init/rild.rc:system/vendor/etc/init/rild.rc \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/init/sensorhub.rc:system/vendor/etc/init/sensorhub.rc \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/init/stp_dump3.rc:system/vendor/etc/init/stp_dump3.rc \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/init/thermal_manager.rc:system/vendor/etc/init/thermal_manager.rc \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/init/wlan_assistant.rc:system/vendor/etc/init/wlan_assistant.rc \
    vendor/mobvoi/mooneye/proprietary/system/vendor/etc/init/wmt_loader.rc:system/vendor/etc/init/wmt_loader.rc \
    vendor/mobvoi/mooneye/proprietary/system/vendor/firmware/0501.fw:system/firmware/0501.fw \
    vendor/mobvoi/mooneye/proprietary/system/vendor/firmware/Cywee.hex:system/firmware/Cywee.hex \
    vendor/mobvoi/mooneye/proprietary/system/vendor/firmware/tp_k_g_mooneye.raw:system/firmware/tp_k_g_mooneye.raw \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/egl/libEGL_mali.so:system/vendor/lib/egl/libEGL_mali.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/egl/libGLESv1_CM_mali.so:system/vendor/lib/egl/libGLESv1_CM_mali.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/egl/libGLESv2_mali.so:system/vendor/lib/egl/libGLESv2_mali.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/android.hardware.bluetooth@1.0-impl.so:system/vendor/lib/hw/android.hardware.bluetooth@1.0-impl.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/android.hardware.gnss@1.0-impl.so:system/vendor/lib/hw/android.hardware.gnss@1.0-impl.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so:system/vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/android.hardware.keymaster@3.0-impl.so:system/vendor/lib/hw/android.hardware.keymaster@3.0-impl.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/android.hardware.power@1.0-impl.so:system/vendor/lib/hw/android.hardware.power@1.0-impl.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/android.hardware.vibrator@1.0-impl.so:system/vendor/lib/hw/android.hardware.vibrator@1.0-impl.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/audio.primary.default.so:system/vendor/lib/hw/audio.primary.default.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/audio.primary.mt2601.so:system/vendor/lib/hw/audio.primary.mt2601.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/audio_policy.stub.so:system/vendor/lib/hw/audio_policy.stub.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/gralloc.default.so:system/vendor/lib/hw/gralloc.default.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/gralloc.mt2601.so:system/vendor/lib/hw/gralloc.mt2601.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/hwcomposer.mt2601.so:system/vendor/lib/hw/hwcomposer.mt2601.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/memtrack.default.so:system/vendor/lib/hw/memtrack.default.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/power.default.so:system/vendor/lib/hw/power.default.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/sensors.cywee.so:system/vendor/lib/hw/sensors.cywee.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/hw/vibrator.default.so:system/vendor/lib/hw/vibrator.default.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libMali.so:system/vendor/lib/libMali.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libaudiocomponentengine.so:system/vendor/lib/libaudiocomponentengine.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libbessound_hd_mtk.so:system/vendor/lib/libbessound_hd_mtk.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libbluetooth_mtk.so:system/vendor/lib/libbluetooth_mtk.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libbluetooth_mtk_pure.so:system/vendor/lib/libbluetooth_mtk_pure.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libbluetooth_relayer.so:system/vendor/lib/libbluetooth_relayer.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libbluetoothem_mtk.so:system/vendor/lib/libbluetoothem_mtk.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libcustom_nvram.so:system/vendor/lib/libcustom_nvram.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libcvsd_mtk.so:system/vendor/lib/libcvsd_mtk.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libdpframework.so:system/vendor/lib/libdpframework.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libfft.so:system/vendor/lib/libfft.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libfile_op.so:system/vendor/lib/libfile_op.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libgralloc_extra.so:system/vendor/lib/libgralloc_extra.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libion_mtk.so:system/vendor/lib/libion_mtk.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libkeystore-engine-wifi-hidl.so:system/vendor/lib/libkeystore-engine-wifi-hidl.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libkeystore-wifi-hidl.so:system/vendor/lib/libkeystore-wifi-hidl.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libmnl.so:system/vendor/lib/libmnl.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libmsbc_mtk.so:system/vendor/lib/libmsbc_mtk.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libmtk_drvb.so:system/vendor/lib/libmtk_drvb.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libmtk_mali_user.so:system/vendor/lib/libmtk_mali_user.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libnvram.so:system/vendor/lib/libnvram.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libnvram_daemon_callback.so:system/vendor/lib/libnvram_daemon_callback.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libnvram_platform.so:system/vendor/lib/libnvram_platform.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/libwifi-hal.so:system/vendor/lib/libwifi-hal.so \
    vendor/mobvoi/mooneye/proprietary/system/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so
